### ISSUE TITLE
Broken windows installer

### ISSUE THREAD

**Issue by ivalylo** [Radeon-ProRender/Blender#2]
Your installer for Windows here
https://pro.radeon.com/en/software/prorender/blender/

is broken. It's something like 40MB and can't be run.

**Comment by zantze** [comment]
I had the same issue when trying to install the 1.4.0 for blender downloaded from their own site. Said something like "This installation package could not be opened". My friend had the same issue.

Turns out there was something wrong with the upload to AMD's server (I assume), because when I downloaded it using a VPN connected to USA (I'm from Finland), it started working immediately.
