### ISSUE TITLE
Where is the source code for RPR and Blender Addon?

### ISSUE THREAD

**Issue by juangea** [Radeon-ProRender/Blender#5]
Hi there.

I would like to know where is the source code of RPR and it's Blender addon.

Cheers!

**Comment by bsavery** [comment]
The renderer source code is not open however you can download an SDK here for free:  https://www.amd.com/en/technologies/radeon-prorender-developers

Addon source code can be inspected by installing the addon and viewing it in the addons folder, it's just python code.

**Comment by juangea** [comment]
Thanks!

How do you connect the addon with the closed source part of the addon so it is GPL compliant?

I may need to do something similar so I want to understand how do yo do this :)

**Comment by bsavery** [comment]
Good question.  
(I should preface this by saying I am not a lawyer)
In short we have the closed source part with it's own python extension that is imported by the open source addon.  If you are doing any heavy computing this is probably desirable anyway

This is a bit of a gray area of the GPL.  I assume you're referring somewhat to the tweet by Ton today.  The issue here is around "linking" code together between GPL code and non GPL code.  https://en.wikipedia.org/wiki/GPL_linking_exception

In addition the unclear part is if a python script that imports a python external library is considered linking.  Some claim this is the case, that to be completely separate you must have them communicate over sockets, files, etc.  Which clearly would make communication painful.  However most interpretations I have seen say that sharing data structures implies linking.  In RPR we simply make external calls, not sharing data.  

What I will say is that Blender and Ton could make this more clear, and say something like "addons must be GPL, but they can call out to private closed source libraries."  Seems like it would satisfy all parties.

**Comment by juangea** [comment]
Thanks for the answer!

I assume that, while you are not a lawyer, AMD has their own lawyers and they factually checked that this procedure is GPL compliant, right?

Thanks for the explanation it is very useful!
